# Generated by Django 6.0 on 2026-01-14 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='item_name',
            field=models.CharField(blank=True, help_text='Product Name or Manual Item Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.batch'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
    ]
